fish/fish/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('myapp.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fish/myapp/urls.py
from django.urls import path
from myapp.views import *
from django.conf.urls import url
from django.contrib.auth.views import LoginView,LogoutView

from . import views

urlpatterns = [
    path(        'login/',        LoginView.as_view(            template_name="myapp/registration/login.html",            ),        name='login'),
    path(        'logout/',        LoginView.as_view(            template_name="myapp/registration/logout.html",            ),        name='logout'),

    path('', index, name='index'),
    path('userlogin/', user_login2, name='user_login'),
    path('managerlogin/', user_login3, name='user_login3'),

    url(r'^User/$',list_user,name='list_user'),
    url(r'^User/create/$', user_create, name='user_create'),
    url(r'^User/(?P<id>\d+)/update/$', user_update, name='user_update'),
    url(r'^User/(?P<id>\d+)/delete/$', user_delete, name='user_delete'),
    url(r'^Folder/$', list_folder, name='list_folder'),
    url(r'^Mail/$',list_mail,name='list_mail'),
    url(r'^Fish/$',list_fish,name='list_fish'),
    url(r'^Fish/Search/$',search_fish,name='search_fish'),
    url(r'^Fish/Upload$',fish_upload2,name='fish_upload'),
    url(r'^Fish/Create$',fish_create,name='fish_create'),
    url(r'^Fish/Process$',processfile,name='processfile'),
    url(r'^Fish/(?P<id>\d+)/Delete$',fish_delete,name='fish_delete'),


    url(r'^Fish/Detail$',details_fish,name='details_fish'),
    url(r'^Mail/create/$', mail_create, name='mail_create'),
    url(r'^Fish/(?P<id>\d+)/shekayat/$', register_shekayat, name='register_shekayat'),
    url(r'^Mail/(?P<id>\d+)/delete/$', mail_delete, name='mail_delete'),
    url(r'^Mail/(?P<id>\d+)/update/$', mail_update, name='mail_update'),
    url(r'^Mail/Sent/$', list_sentmail, name='list_sentmail'),
    url(r'^Mail/Status/$', list_unread_mail, name='list_unread_mail'),
    url(r'^Mail/System/$', list_sysmail, name='list_sysmail'),
    url(r'^MailFile/$', file_upload, name='file_upload'),
    url(r'^upload/$', handle_file_upload, name='handle_file_upload'),
    url(r'^file/$', file_upload_doc, name='file_upload_doc'),
    url(r'^personel/upload/$', insert_personel_data_from_csv, name='insert_personel_data_from_csv'),
    url(r'^personel/files/(?P<id>\d+)/remove$', remove_person_file, name='remove_person_file'),
    url(r'^personel/files/$', login_to_load_file, name='login_to_load_file'),
    url(r'^personel/$', list_personel, name='list_personel'),
    url(r'^personel/brief$', list_personel_breif, name='list_personel_breif'),
    url(r'^personel/brief/All$', list_personel_breif_all, name='list_personel_breif_all'),
    url(r'^personel/brief/getInfo$', get_personel_breig_info, name='get_personel_breig_info'),
    url(r'^personel/brief/getInfo/All$', get_personel_breig_info_all, name='get_personel_breig_info_all'),
    url(r'^personel/(?P<id>\d+)/profile$', view_profile, name='view_profile'),
    url(r'^personel/Att$', view_att, name='view_att'),
    url(r'^personel/SaveInfo/$', save_personel_att, name='save_personel_att'),
    url(r'^personel/GetMamnager$', get_manager_by_makan, name='get_manager_by_makan'),

    url(r'^personel/LoadDate/$', view_att, name='view_att'),
    url(r'^personel/(?P<id>\d+)/Delete$', delete_personel, name='delete_personel'),
    url(r'^personel/(?P<id>\d+)/Suspend$', suspend_personel, name='suspend_personel'),
    url(r'^Hozur/create/$', hozur_create, name='hozur_create'),
    url(r'^Hozur/GetTitles/$', getTitle, name='getTitle'),
    url(r'^Hozur/Calendar/$', show_hozur_calendar, name='show_hozur_calendar'),
    url(r'^Hozur/GetInfo/$', get_personel_calendar_info, name='get_personel_calendar_info'),
    url(r'^Hozur/GetDetails/$', get_hozur_list_detail, name='get_hozur_list_detail'),
    url(r'^Profile/Create/$', personel_create, name='create_profile'),
    url(r'^Profile/(?P<id>\d+)/Update/$', update_personel, name='update_personel'),
    url(r'^personel/Search/$',search_personel,name='search_personel'),
    url(r'^Hozur/Success/$',show_hozur_success,name='show_hozur_success'),
    url(r'^Hozur/Delete$',hozur_delete,name='hozur_delete'),
    url(r'^api/v1/assets$',list_assets,name='list_assets'),
    url(r'^api/v1/ita$',send_ita_view,name='send_ita_view'),







]

fish/myapp/models/assetcategory.py
from django.db import models


class AssetCategory(models.Model):
    name=models.CharField("نام",max_length = 50)
    code=models.CharField("کد",max_length = 50)
    description=models.CharField("توضیحات",max_length = 50)
    priority=models.IntegerField("اولویت", null=True)
    isPartOf = models.ForeignKey('self',on_delete=models.CASCADE,verbose_name="زیر مجموعه",null=True,blank=True)
    def __str__(self):
        return self.name

    class Meta:
       db_table = "assetcategory"

fish/myapp/models/purchaserequest.py
from django.db import models
from datetime import datetime
from myapp.models.Asset import Asset
import jdatetime
class PurchaseRequest(models.Model):
    def get_pstatus(self):
                 if(self.PurchaseRequestAssetNot==True):
                     return "<i class='fa fa-check'></i>								"
                 else:
                     return "<i class='fa fa-close'></i>"
    def getQTY(self):
        if(self.PurchaseRequestAssetQty):
            return self.PurchaseRequestAssetQty
        return self.PurchaseRequestAssetQtyNot

    def get_dateCreated_jalali(self):
        return jdatetime.date.fromgregorian(date=self.PurchaseRequestDateTo)
    def is_in_manager(self):
        return (self.PurchaseRequestRequestedUser.userId.groups.filter(name= 'manager').exists())
    Requested=1
    onHold=2
    Draft=3
    Assigned=4
    Open=5
    workInProgress=6
    closedComplete=7
    closedIncomplete=8
    waitingForPart=9
    invisible=-1
    Highest=1
    High=2
    Medium=3
    Low=4
    Lowest=5
    Status=(
         (Requested,'درخواست شده')  ,
         (onHold,'متوقف'),
         (Assigned,'تخصیص داده شده'),
         (Open,'باز'),
         (workInProgress,'در حال پیشرفت'),
         (closedComplete,'بسته شده کامل'),
         (closedIncomplete,'بسته شده، ناقص'),
         (waitingForPart,'در انتظار قطعه'),

     )
    PurchaseRequestStatus=models.IntegerField("وضعیت درخواست", choices=Status,null=True,blank=True)
    PurchaseRequestPartName=models.ForeignKey("Part",on_delete=models.CASCADE,null=True,blank=True,related_name="RequestedPart",verbose_name="مشخصات قطعه")
    PurchaseRequestMoreInfo=models.CharField("اطلاعات بیشتر",max_length = 100,null=True,blank=True)
    PurchaseRequestAssetNotInInventory=models.CharField("ناموجود در انبار؟ اطلاعات بیشتری شرح دهید",max_length = 100,null=True,blank=True)
    #not in inventory qty
    PurchaseRequestAssetQty=models.FloatField("تعداد")
    PurchaseRequestAssetQtyNot=models.FloatField("کمیت",null=True,blank=True)
    PurchaseRequestAssetNot=models.BooleanField("در صورت عدم تهیه تولید دچار وقفه میشود",default=False)
    PurchaseRequestNotInList=models.BooleanField(default=False,null=True)




    # PurchaseRequestWO = models.ForeignKey('WorkOrder',on_delete=models.CASCADE,null=True,blank=True,related_name="ImpactedWO",verbose_name="درخواست مربوطه")
    PurchaseRequestAsset = models.ForeignKey('Asset',on_delete=models.CASCADE,null=True,blank=True,related_name="ImpactedAsset",verbose_name="تجهیز")
    PurchaseRequestAssetMakan = models.ForeignKey('Asset',on_delete=models.CASCADE,null=True,blank=True,related_name="ImpactedLocation")
    PurchaseRequestDateTo = models.DateField("مهلت تا تاریخ", blank=True,null=True)
    PurchaseRequestDateFrom = models.DateField("تاریخ درخواست")
    # PurchaseRequestDate2 = models.DateField("مهلت تا تاریخ",default=datetime.now, blank=True,null=True)
    settingTimestamp=models.DateTimeField(auto_now_add=True)
    PurchaseRequestRequestedUser = models.ForeignKey('SysUser',on_delete=models.CASCADE,verbose_name="کاربر درخواست کننده",null=True,related_name="PurchaseRequestdUser")
    PurchaseRequestAuthUser = models.ForeignKey('SysUser',on_delete=models.CASCADE,verbose_name="کاربر مجاز",null=True,blank=True,related_name="PurchaseRequestAuthUser")
    def __str__(self):
        return self.id

    class Meta:
       db_table = "purchaserequest"
# class PurchaseRequestHistory(models.Model):
#     PurchaseRequestID=models.ForeignKey(PurchaseRequest,on_delete=models.CASCADE,null=True,blank=True)
#     PurchaseHistoryDate=models.DateTimeField(auto_now_add=True)
#     class Meta:
#        db_table = "purchaserequesthistory"

fish/myapp/forms.py
from django import forms
from myapp.models import *
from django.conf import settings
import logging
from django.forms import ModelForm, inlineformset_factory
from django.contrib.auth.models import Group
class SysUserForm(forms.ModelForm):
    #CustomerId = forms.ModelChoiceField(queryset=Customer.objects.all())



    class Meta:
        model = SysUser
        fields = '__all__'
class MessageForm(forms.ModelForm):
    toUser = forms.ModelChoiceField(label="مخاطب",queryset=SysUser.objects.all(),empty_label='به کی')
    def clean_messageStatus(self):
        if(self.isupdated):
            messageStatus=3
        else:
            messageStatus=2

        return messageStatus



    class Meta:
        model = Message
        fields = '__all__'

class HozurForm(forms.ModelForm):
    name=forms.CharField(widget=forms.Textarea())
   

    class Meta:
        model = HozurGhiab
        fields = '__all__'
class PersonelForm(forms.ModelForm):

    class Meta:
        model = Personnel
        # fields = '__all__'
        fields = ['manager', 'saloon','PNumber','FName','LName','NCode','Father','title']

class MessageForm(forms.Form):
    body = forms.CharField(widget=forms.Textarea())
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

fish/myapp/views/dashboardview.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.template.loader import render_to_string
from myapp.business.UserUtility import *
from django.contrib.auth.decorators import login_required
from myapp.models import SysUser
# @login_required
def index(request):
    month=['فروردین','ارديبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند']
    # UserUtility.get_user_list(request)
    # return render(request,"myapp/index.html",{"today" : today})
    return render(request,"myapp/entrance/login.html",{"today" : month})

fish/myapp/views/folderview.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.db.models import Sum
import jdatetime
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.views.decorators import csrf
import django.core.serializers
import logging
from django.conf import settings
from myapp.models.users import *
from django.views import View
import json
from django.forms.models import model_to_dict
from myapp.forms import SysUserForm
# from myapp.forms import SysUserImageForm
from django.urls import reverse_lazy
from django.db import transaction
from django.views.decorators.csrf import csrf_exempt
from myapp.business.mail import Mail
from myapp.business.UserUtility import *
from django.contrib.auth.decorators import login_required
from myapp.business.DateJob import *
from django.core.paginator  import *
from django.contrib.auth.models import User
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

def list_folder(request):
    return render(request, 'myapp/folders/folderList.html', {})

fish/myapp/views/mailfileview.py
'''
 fmt = getattr(settings, 'LOG_FORMAT', None)
 lvl = getattr(settings, 'LOG_LEVEL', logging.DEBUG)

 logging.basicConfig(format=fmt, level=lvl)
 logging.debug(newobject.OrderId.id)
 '''

from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.template.loader import render_to_string
import os
import jdatetime
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.views.decorators import csrf
import django.core.serializers
import logging
from django.conf import settings
from myapp.models.message import *
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.views import View
#from django.core import serializers
import json
from django.forms.models import model_to_dict
# from myapp.forms import WoFileForm
from django.views.decorators.http import require_POST
from django.core.files.storage import default_storage
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.context_processors import PermWrapper
from rest_framework.decorators import api_view
# from myapp.api.WOSerializer import *
from rest_framework.response import Response

###################################################################


###################################################################    ###################################################################
def file_upload(request):
    if request.method == 'POST':
        print("here!!!",request.FILES)
        my_file=request.FILES.get('file')
        msg=MessageFile.objects.create(msgFile=my_file)
        data=dict()
        data["id"]=msg.id
        return JsonResponse(data)
        # return HttpResponse('')
    return JsonResponse({'post':'fasle'})
class MessageUploadView(View):
    def get(self, request):
        # books = MessageFile.objects.all()
        # return render(request, 'myapp/msg_file/woFileList.html', {'woFiles': books})
        pass

    def post(self, request,Id=None):
        print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
        from django.core.exceptions import ValidationError
        data=dict()
        # fmt = getattr(settings, 'LOG_FORMAT', None)
        # lvl = getattr(settings, 'LOG_LEVEL', logging.DEBUG)
        company= get_object_or_404(WorkOrder, id=Id)
        # logging.basicConfig(format=fmt, level=lvl)
        # logging.debug( request.FILES)
        valid_extensions = ['.pdf', '.doc', '.docx', '.jpg', '.png', '.xlsx', '.xls','.gif','.aac']
        ext = os.path.splitext(request.FILES['woFile'].name)[1]
        if not ext.lower() in valid_extensions:
            raise ValidationError(u'Unsupported file extension.')
        else:
            save_path = os.path.join(settings.MEDIA_ROOT,'documents', request.FILES['msgFile'].name)
            path = default_storage.save(save_path, request.FILES['woFile'])
            document = MessageFile.objects.create(msgFile='documents/'+request.FILES['msgFile'].name, woFileworkorder=company)
            #data = {'is_valid': True, 'name': document.woFile.name, 'url': document.woFile.url,'ext':ext,'size':" MB {0:.2f}".format(document.woFile.size/1048576)}
            # books = MessageFile.objects.filter(woFileworkorder=Id)
            # data['html_woFile_list'] = render_to_string('myapp/msg_file/partialWoFileList.html', {
            #       'msgFiles': books})
            # data['is_valid']=True

        return JsonResponse(data)






@api_view(['GET'])
def wofile_collection(request,id):
    if request.method == 'GET':
        print("reached task")
        posts = MessageFile.objects.filter(woFileworkorder=id)
        serializer = MessageFileSerializer(posts, many=True)

        return Response(serializer.data)
@api_view(['GET'])
def wofile_detail_collection(request,id):
    if request.method == 'GET':
        # print("!23")
        posts = MessageFile.objects.get(id=id)
        serializer = MessageFileSerializer(posts)

        return Response(serializer.data)

@api_view(['POST'])
def woFile_post(request,Id=None):
        print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
        from django.core.exceptions import ValidationError
        data=dict()
        print(request.FILES['woFile'],'$$$$$$$$$$$$$$$$$$$$$$$$$$$$$')
        # fmt = getattr(settings, 'LOG_FORMAT', None)
        # lvl = getattr(settings, 'LOG_LEVEL', logging.DEBUG)
        company= get_object_or_404(WorkOrder, id=Id)
        # logging.basicConfig(format=fmt, level=lvl)

        # valid_extensions = ['.pdf', '.doc', '.docx', '.jpg', '.png', '.xlsx', '.xls','.gif']
        # ext = os.path.splitext(request.FILES['woFile'].name)[1]
        # if not ext.lower() in valid_extensions:
        #     raise ValidationError(u'Unsupported file extension.')
        # else:
        save_path = os.path.join(settings.MEDIA_ROOT,'documents', request.FILES['woFile'].name)
        path = default_storage.save(save_path, request.FILES['woFile'])
        document = MessageFile.objects.create(woFile='documents/'+request.FILES['woFile'].name, woFileworkorder=company)
        #data = {'is_valid': True, 'name': document.woFile.name, 'url': document.woFile.url,'ext':ext,'size':" MB {0:.2f}".format(document.woFile.size/1048576)}
        books = MessageFile.objects.filter(woFileworkorder=Id)
        data['html_woFile_list'] = render_to_string('myapp/workorder_file/partialWoFileList.html', {
              'woFiles': books})
        data['is_valid']=True

        print("Ok!!!!!!!!!!!!!!")

        return JsonResponse(data)

fish/myapp/templates/myapp/purchase_request/partialPurchaseRequestCreate.html
<form method="post" action="{% url 'purchaseRequest_create'   %}" class="js-purchaseRequest-create-form" autocomplete="off">
  {% csrf_token %}
  <div class="modal-header " style="background:#ccc">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">جدید</h4>
  </div>
  <div class="modal-body">
   {% include 'myapp/purchase_request/partialPurchaseRequestForm.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default">انصراف</button>
    <button type="submit" class="btn btn-primary" >ذخیره</button>
  </div>
</form>

fish/myapp/templates/myapp/purchase_request/partialPurchaseRequestDelete.html
<form method="post" action="{% url 'purchaseRequest_delete' purchaseRequest.id %}" class="js-purchaseRequest-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">حذف</h4>
  </div>
  <div class="modal-body">
    <p class="lead">از عمل حذف مطمین هستید؟  <strong>{{ rfq.id }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-danger"> حذف</button>
    <button type="button" class="btn btn-default" data-dismiss="modal">بستن</button>
  </div>
</form>

fish/myapp/templates/myapp/purchase_request/partialPurchaseRequestForm.html
{% load widget_tweaks %}
<div class="row">

<div class="col-sm-12 b-r">
  <div class="row">
    <div class="col-sm-2 b-r">
      {% load static %}
      <img src="{% static 'img/pr.png' %}" width="50%" height="50%" / >
      <input type=hidden name='lastPurchaseRequestid' id='lastPurchaseRequestid' />





    </div>
    <div class="col-sm-6">
      <div class="form-group">

      <label>{{form.PurchaseRequestPartName.label}}</label>
      {{form.PurchaseRequestPartName.as_hidden }}
      {% render_field form.mypart class='form-control advanced2AutoComplete' placeholder='جستجو کنید' autocomplete='off'  %}
      </div>
      {% if is_manager %}
      <div class="form-group">

      <label>{{form.PurchaseRequestStatus.label}}</label>

      {{form.PurchaseRequestStatus | add_class:"form-control"}}

      </div>
      {% endif %}
    </div>
    <div class="col-sm-4">
      <div class="form-group">
      <label>{{form.PurchaseRequestAssetQty.label}}</label>
      {{form.PurchaseRequestAssetQty| add_class:"form-control" }}
      </div>

    </div>

  </div>
  <hr>
  <div class="row exist">
    <div class="col-sm-12">
      <div class="form-group">


      <label>اطلاعات بیشتر</label>
      {{form.PurchaseRequestMoreInfo| add_class:"form-control" }}
      </div>

    </div>

  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="panel-body">
        <div class='row'>
          <div class='col-lg-12'>
            <div class="panel panel-info">
                 <div class="panel-heading">
                     <i class="fa fa-info-circle"></i> اطلاعات مکانی
                 </div>
                 <div class="panel-body">
                     <div class="row">
                       <div class="col-lg-6">
                                           <div class="form-group">
                                             {{form.PurchaseRequestAssetNot }}
                                             <label>{{form.PurchaseRequestAssetNot.label}}</label>


                                           </div>
                                           <div class="form-group">
                                             <label>{{form.PurchaseRequestWO.label}}</label>
                                             {{form.PurchaseRequestWO.as_hidden }}
                                             {{form.mywo| add_class:"form-control" }}
                                           </div>
                                           <div class="form-group">
                                             <label>{{form.PurchaseRequestWO.label}}</label>
                                             {% render_field form.PurchaseRequestRequestedUser class="form-control selectpicker" data-show-subtext="true" data-live-search="true"  %}
                                           </div>




                       </div>
                       <div class="col-lg-6">

                         <div class="form-group">
                           <label>{{form.PurchaseRequestAssetMakan.label}}</label>
                            {% render_field form.PurchaseRequestAssetMakan class="form-control selectpicker" data-show-subtext="true" data-live-search="true"  %}
                         </div>
                         <div class="form-group">
                           <label>{{form.PurchaseRequestAsset.label}}</label>
                             {% render_field form.PurchaseRequestAsset class="form-control selectpicker" data-show-subtext="true" data-live-search="true"  %}
                         </div>
                         <div class="form-group">
                           <label>{{form.PurchaseRequestDateTo.label}}</label>
                           {{form.PurchaseRequestDateTo| add_class:"form-control" }}
                         </div>


                       </div>

                     </div>
                 </div>

            </div>




          </div>
        </div>

         </div>

    </div>

  </div>




</div>

</div>

fish/myapp/templates/myapp/purchase_request/partialPurchaseRequestList.html
{% for c in rfq %}

<tr>
<td></td>
<td>{{c.id}}</td>
<td>{{c.PurchaseRequestAsset}}</td>
<td>{{c.PurchaseRequestPartName}}</td>

<td>{{c.PurchaseRequestAssetQty}}</td>
 <td>{% autoescape off %}{{c.get_pstatus}}{% endautoescape %}</td>
 <td>{{c.get_PurchaseRequestStatus_display}}</td>

 <td>{{c.PurchaseRequestRequestedUser}}</td>
 <td>{{c.get_dateCreated_jalali}}</td>







 <td><button type="button"
              class="btn btn-warning btn-sm js-update-purchaseRequest"
              data-url="{% url 'purchaseRequest_update' c.id %}">
        <span class="glyphicon glyphicon-pencil"></span> ویرایش
      </button>
      <button type="button"
                   class="btn btn-danger btn-sm js-delete-purchaseRequest"
                   data-url="{% url 'purchaseRequest_delete' c.id %}">
             <span class="glyphicon glyphicon-trash"></span> حذف
           </button>
    </td>
</tr>
{% empty %}
<tr>
 <td colspan="10" class="text-center ">هیچ موردی یافت نشد</td>
</tr>

{% endfor %}

fish/myapp/templates/myapp/purchase_request/partialPurchaseRequestUpdate.html
<form method="post" action="{% url 'purchaseRequest_update' form.instance.id %}" class="js-purchaseRequest-update-form" autocomplete="off">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">ویرایش</h4>
  </div>
  <div class="modal-body">
    {% include 'myapp/purchase_request/partialPurchaseRequestForm.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">بستن</button>
    <button type="submit" class="btn btn-primary">ویرایش</button>
  </div>
</form>

fish/myapp/templates/myapp/purchase_request/partialWoPagination.html
{% if wo.has_other_pages %}

<ul class="pagination">
{% if wo.has_previous %}
<li><a href="#" data-url="{% url pageType %}?page={{ wo.previous_page_number }}" class="wo_month_paginator2">&laquo;</a></li>
{% else %}
<li class="disabled"><span>&laquo;</span></li>
{% endif %}
{% for i in wo.paginator.page_range %}
{% if users.number == i %}
<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
{% else %}
<li><a href="#" data-url="{% url pageType %}?page={{ i }}" class="wo_month_paginator2">{{ i }}</a></li>
{% endif %}
{% endfor %}
{% if wo.has_next %}
<li><a href="#" data-url="{% url pageType %}?page={{ wo.next_page_number }}" class="wo_month_paginator2"">&raquo;</a></li>
{% else %}
<li class="disabled"><span>&raquo;</span></li>
{% endif %}
</ul>
{% endif %}
<script type="text/javascript">
  $(".wo_month_paginator2").click(function()
  {

    //console.log($(this).attr("data-url"));
    $.ajax({
      url: $(this).attr("data-url"),

      type: "get",
      dataType: 'json',
      success: function (data) {
        if (data.form_is_valid) {
          //alert("Company created!");  // <-- This is just a placeholder for now for testing
          $("#tbody_company").empty();
          $("#tbody_company").html(data.html_swo_list);
           $(".woPaging").html(data.html_swo_paginator);
           $("#modal-company").modal("hide");


         // console.log(data.html_wo_list);
        }
        else {

          $("#company-table tbody").html(data.html_wo_list);
          $("#modal-company .modal-content").html(data.html_wo_form);
        }
      }
    });

  });


</script>