fish/fish/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('myapp.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fish/myapp/urls.py
from django.urls import path
from myapp.views import *
from django.conf.urls import url
from django.contrib.auth.views import LoginView,LogoutView

from . import views

urlpatterns = [
    path(        'login/',        LoginView.as_view(            template_name="myapp/registration/login.html",            ),        name='login'),
    path(        'logout/',        LoginView.as_view(            template_name="myapp/registration/logout.html",            ),        name='logout'),

    path('', index, name='index'),
    path('userlogin/', user_login2, name='user_login'),
    path('managerlogin/', user_login3, name='user_login3'),

    url(r'^User/$',list_user,name='list_user'),
    url(r'^User/create/$', user_create, name='user_create'),
    url(r'^User/(?P<id>\d+)/update/$', user_update, name='user_update'),
    url(r'^User/(?P<id>\d+)/delete/$', user_delete, name='user_delete'),
    url(r'^Folder/$', list_folder, name='list_folder'),
    url(r'^Mail/$',list_mail,name='list_mail'),
    url(r'^Fish/$',list_fish,name='list_fish'),
    url(r'^Fish/Search/$',search_fish,name='search_fish'),
    url(r'^Fish/Upload$',fish_upload2,name='fish_upload'),
    url(r'^Fish/Create$',fish_create,name='fish_create'),
    url(r'^Fish/Process$',processfile,name='processfile'),
    url(r'^Fish/(?P<id>\d+)/Delete$',fish_delete,name='fish_delete'),


    url(r'^Fish/Detail$',details_fish,name='details_fish'),
    url(r'^Mail/create/$', mail_create, name='mail_create'),
    url(r'^Fish/(?P<id>\d+)/shekayat/$', register_shekayat, name='register_shekayat'),
    url(r'^Mail/(?P<id>\d+)/delete/$', mail_delete, name='mail_delete'),
    url(r'^Mail/(?P<id>\d+)/update/$', mail_update, name='mail_update'),
    url(r'^Mail/Sent/$', list_sentmail, name='list_sentmail'),
    url(r'^Mail/Status/$', list_unread_mail, name='list_unread_mail'),
    url(r'^Mail/System/$', list_sysmail, name='list_sysmail'),
    url(r'^MailFile/$', file_upload, name='file_upload'),
    url(r'^upload/$', handle_file_upload, name='handle_file_upload'),
    url(r'^file/$', file_upload_doc, name='file_upload_doc'),
    url(r'^personel/upload/$', insert_personel_data_from_csv, name='insert_personel_data_from_csv'),
    url(r'^personel/files/(?P<id>\d+)/remove$', remove_person_file, name='remove_person_file'),
    url(r'^personel/files/$', login_to_load_file, name='login_to_load_file'),
    url(r'^personel/$', list_personel, name='list_personel'),
    url(r'^personel/brief$', list_personel_breif, name='list_personel_breif'),
    url(r'^personel/brief/All$', list_personel_breif_all, name='list_personel_breif_all'),
    url(r'^personel/brief/getInfo$', get_personel_breig_info, name='get_personel_breig_info'),
    url(r'^personel/brief/getInfo/All$', get_personel_breig_info_all, name='get_personel_breig_info_all'),
    url(r'^personel/(?P<id>\d+)/profile$', view_profile, name='view_profile'),
    url(r'^personel/Att$', view_att, name='view_att'),
    url(r'^personel/SaveInfo/$', save_personel_att, name='save_personel_att'),
    url(r'^personel/GetMamnager$', get_manager_by_makan, name='get_manager_by_makan'),

    url(r'^personel/LoadDate/$', view_att, name='view_att'),
    url(r'^personel/(?P<id>\d+)/Delete$', delete_personel, name='delete_personel'),
    url(r'^personel/(?P<id>\d+)/Suspend$', suspend_personel, name='suspend_personel'),
    url(r'^Hozur/create/$', hozur_create, name='hozur_create'),
    url(r'^Hozur/GetTitles/$', getTitle, name='getTitle'),
    url(r'^Hozur/Calendar/$', show_hozur_calendar, name='show_hozur_calendar'),
    url(r'^Hozur/GetInfo/$', get_personel_calendar_info, name='get_personel_calendar_info'),
    url(r'^Hozur/GetDetails/$', get_hozur_list_detail, name='get_hozur_list_detail'),
    url(r'^Profile/Create/$', personel_create, name='create_profile'),
    url(r'^Profile/(?P<id>\d+)/Update/$', update_personel, name='update_personel'),
    url(r'^personel/Search/$',search_personel,name='search_personel'),
    url(r'^Hozur/Success/$',show_hozur_success,name='show_hozur_success'),
    url(r'^Hozur/Delete$',hozur_delete,name='hozur_delete'),
    url(r'^api/v1/assets$',list_assets,name='list_assets'),
    url(r'^api/v1/ita$',send_ita_view,name='send_ita_view'),







]

fish/myapp/models/users.py
#python manage.py makemigrations
#After that you just have to run migrate command for syncing database .

#python manage.py migrate --run-syncdb
from django.db import models
from datetime import datetime
import os
from django.contrib.auth.models import User
import jdatetime
from django.utils.timezone import now
# from cmms.models.Asset import *
class testuser(models.Model):
    # password=models.CharField(max_length=20)
    massage=models.CharField("مشخصات کامل",max_length = 50)
    class Meta:
        db_table="testuser"


class SysUser(models.Model):
    def __str__(self):
        return "{}".format(self.fullName)
    def get_userStatus(self):
                 if(self.userStatus==True):
                     return "<span class='badge badge-success'><span class='mr-1 fa fa-check'></span>کامل شد</span>"
                 else:
                     return "<span class='badge badge-success'><span class='mr-1 fa fa-check'></span>کامل شد</span>"
    def getName(self):

        xxxx=UserGroups.objects.filter(userUserGroups=self.id)
        st=[]
        for i in xxxx:
            st.append(i.groupUserGroups)
        # print(''.join(str(e) for e in st))
        return '<br/>'.join(str(e) for e in st)


    Dashboard=1
    WorkOrderAssignedToMe=2
    MessageCenterInbox=3
    WorkOrders=4
    Location=(
        (Dashboard,'داشبورد'),
        (WorkOrderAssignedToMe,'درخواستهای انتسابی به من'),
        (MessageCenterInbox,'صندوق ورودی پیامها'),
        (WorkOrders,'درخواست'),
    )
    userId = models.OneToOneField(User, on_delete=models.CASCADE,null=True,blank=True)
    password=models.CharField(max_length=20)
    token=models.CharField(max_length=20,null=True,blank=True)
    fullName=models.CharField("مشخصات کامل",max_length = 50)
    personalCode=models.CharField("کد پرسنلی",max_length = 50)
    title=models.CharField("نام کاربری",max_length = 50,null=True,blank=True)
    email=models.EmailField("ایمیل",max_length=70,blank=True, null= True, unique= True)
    profileImage = models.ImageField(upload_to='images/',default=None,blank=True)

    userStatus=models.BooleanField("وضعیت",default=True)

    class Meta:
        db_table="sysusers"
        ordering = ['title']



class UserGroup(models.Model):
    def __str__(self):
        if(self.userUserLocation):
            return "{}:{}".format(self.userGroupName,self.userUserLocation)
        else:
            return "{}".format(self.userGroupName)

    userGroupCode=models.CharField("کد",max_length=50)
    userGroupName=models.CharField("نام",max_length=50)

    userGroupIsPartOF=models.ForeignKey('self',on_delete=models.CASCADE,blank=True,null=True,verbose_name='زیرمجموعه')

    class Meta:
        db_table="usergroup"

class UserGroups(models.Model):


    userUserGroups=models.ForeignKey(SysUser,on_delete=models.CASCADE,blank=True,null=True)
    groupUserGroups=models.ForeignKey(UserGroup,on_delete=models.CASCADE,blank=True,null=True)
    class Meta:
        db_table="usergroups"
class UserFile(models.Model):
    def get_ext(self):
        v=os.path.splitext(self.userFile.name)
        return v[len(v)-1]
    def get_size(self):
        return " MB {0:.2f}".format(self.userFile.size/1048576)

    userFile=models.FileField(upload_to='documents/')
    userFileUser=models.ForeignKey(SysUser,on_delete=models.CASCADE,blank=True,null=True)
    userFiledateAdded=models.DateTimeField(auto_now_add=True)
    class Meta:
        db_table="userfile"


class Personnel(models.Model):
    manager=models.ForeignKey('SysUser',on_delete=models.SET_NULL,related_name='sarshift',null=True,blank=True)
    saloon=models.ForeignKey('Asset',on_delete=models.SET_NULL,related_name='saloon',null=True,blank=True)
    Pid = models.IntegerField(null=True,blank=True)
    PNumber = models.CharField(max_length=50, blank=True, null=True)
    CpCode = models.IntegerField(null=True,blank=True)
    BranchCode = models.IntegerField(null=True,blank=True)
    CardNo = models.IntegerField(blank=True, null=True)
    FName = models.CharField(max_length=40, blank=True, null=True)
    LName = models.CharField(max_length=50, blank=True, null=True)
    NCode = models.CharField(max_length=10, blank=True, null=True)
    BirthDate = models.CharField(max_length=10, blank=True, null=True)
    Father = models.CharField(max_length=30, blank=True, null=True)
    IdCardNo = models.BigIntegerField(blank=True, null=True)
    IssuedFrom = models.CharField(max_length=30, blank=True, null=True)
    BirthPlace = models.CharField(max_length=30, blank=True, null=True)
    Gender = models.CharField(max_length=1, blank=True, null=True)
    Nationality = models.SmallIntegerField(blank=True, null=True)
    Country = models.CharField(max_length=20, blank=True, null=True)
    Tel = models.CharField(max_length=12, blank=True, null=True)
    Mobile = models.CharField(max_length=11, blank=True, null=True)
    PostalCode = models.BigIntegerField(blank=True, null=True)
    Address = models.CharField(max_length=200, blank=True, null=True)
    Kol = models.IntegerField(blank=True, null=True)
    Moin = models.IntegerField(blank=True, null=True)
    GTaf = models.IntegerField(blank=True, null=True)
    CTaf = models.IntegerField(blank=True, null=True)
    Markaz = models.IntegerField(blank=True, null=True)
    Dayere = models.IntegerField(blank=True, null=True)
    Picture = models.ImageField(blank=True, null=True)
    GruopCode = models.CharField(max_length=12, blank=True, null=True)
    OrganizCode = models.CharField(max_length=20, blank=True, null=True)
    TempEmploymentDate = models.CharField(max_length=10, blank=True, null=True)
    PermanentEmplymentDate = models.CharField(max_length=10, blank=True, null=True)
    Ekhrajdate = models.CharField(max_length=10, blank=True, null=True)
    ContractStartDate = models.CharField(max_length=10, blank=True, null=True)
    ContractFinishDate = models.CharField(max_length=10, blank=True, null=True)
    LeaveWorkDate = models.CharField(max_length=10, blank=True, null=True)
    RetiredDate = models.CharField(max_length=10, blank=True, null=True)
    DieDate = models.CharField(max_length=10, blank=True, null=True)
    InsuranceDate = models.CharField(max_length=10, blank=True, null=True)
    Consideration = models.CharField(max_length=250, blank=True, null=True)
    InsuranceNo = models.CharField(max_length=10, blank=True, null=True)
    InsuranceType = models.SmallIntegerField(blank=True, null=True)
    isActive = models.BooleanField(blank=True, null=True)
    FNameEn = models.CharField(max_length=40, blank=True, null=True)
    LNameEn = models.CharField(max_length=50, blank=True, null=True)
    Countryid = models.SmallIntegerField(blank=True, null=True)
    SanavatMonth = models.SmallIntegerField(blank=True, null=True)
    CpCodeSanad = models.IntegerField(blank=True, null=True)
    WebPass = models.CharField(max_length=100, blank=True, null=True)
    TelegramNumber = models.CharField(max_length=11, blank=True, null=True)
    Shift = models.CharField(max_length=2, blank=True, null=True)
    title = models.IntegerField(

        choices=[
            (0, 'سرشیفت'),
            (1, 'مقدمات'),
            (2, 'پاساژ'),
            (3, 'فبنیشر'),
            (4, 'سردافر'),
            (5, 'رینگ'),
            (6, 'لاکنی'),
            (7, 'دولاتاب'),
            (8, 'اتوکنر'),
            (9, 'خدمات'),
            (10, 'ssm'),
            (11, 'هیت ست'),
            (12, 'تاپس'),
            (13, 'سرپرست'),
            (14, 'آزمایشگاه'),
            (15, 'رنگکشی'),
            (16, 'آبگیر'),
            (17, 'کوب'),
            (18, 'رزرو دیگ'),
            (19, 'استلام'),
            (20, 'کوب کوچک'),
            (21, 'لیفتراک'),
            (22, 'پرس ضایعات'),
            (23, 'پرس و خشک کن'),
            (24, 'لیفتراک ریسندگی'),
            (25, 'کاردینگ'),
            (26, 'ریبریکر'),




        ],
        null=True,blank=True
    )




    def __str__(self):
        return f"{self.FName} {self.LName}"
class PersonelFile(models.Model):
    def get_ext(self):
        v=os.path.splitext(self.woFile.name)
        return v[len(v)-1]
    def get_name(self):
        return os.path.basename(str(self.msgFile))
    def get_size(self):
        return " MB {0:.2f}".format(self.woFile.size/1048576)

    msgFile=models.FileField(upload_to='documents/Personel/%Y/%m/%d',max_length=200)
    msgFilePersonel=models.ForeignKey(Personnel, verbose_name="personel_file", on_delete=models.CASCADE,blank=True,null=True)
    msgFiledateAdded=models.DateTimeField(auto_now_add=True)
    msgFiledtype=models.IntegerField()
    msgFileName=models.CharField(max_length=100,blank=True,null=True)
    class Meta:
        db_table="personelfile"
class HozurGhiab(models.Model):
    person=models.ForeignKey('Personnel',on_delete=models.CASCADE,related_name='person_hozur')
    registerd_by=models.ForeignKey('SysUser',on_delete=models.SET_NULL,related_name='manager',null=True,blank=True)
    incom_time = models.TimeField()
    outcome_time = models.TimeField()
    hdate = models.DateField(default=datetime.now().date())
    registerd_date = models.DateTimeField(auto_now_add=True)
    hozur = models.BooleanField(default=False)
    estehghaghi = models.BooleanField(default=False)
    estelaji = models.BooleanField(default=False)
    is_ezafekar=models.BooleanField(default=False)
    title=models.IntegerField( choices=[
            (0, 'سرشیفت'),
            (1, 'مقدمات'),
            (2, 'پاساژ'),
            (3, 'فبنیشر'),
            (4, 'سردافر'),
            (5, 'رینگ'),
            (6, 'لاکنی'),
            (7, 'دولاتاب'),
            (8, 'اتوکنر'),
            (9, 'خدمات'),
            (10, 'ssm'),
            (11, 'هیت ست'),
            (12, 'تاپس'),
            (13, 'سرپرست'),
            (14, 'آزمایشگاه'),
            (15, 'رنگکشی'),
            (16, 'آبگیر'),
            (17, 'کوب'),
            (18, 'رزرو دیگ'),
            (19, 'استلام'),
            (20, 'کوب کوچک'),
            (21, 'لیفتراک'),
            (22, 'پرس ضایعات'),

fish/myapp/forms.py
from django import forms
from myapp.models import *
from django.conf import settings
import logging
from django.forms import ModelForm, inlineformset_factory
from django.contrib.auth.models import Group
class SysUserForm(forms.ModelForm):
    #CustomerId = forms.ModelChoiceField(queryset=Customer.objects.all())



    class Meta:
        model = SysUser
        fields = '__all__'
class MessageForm(forms.ModelForm):
    toUser = forms.ModelChoiceField(label="مخاطب",queryset=SysUser.objects.all(),empty_label='به کی')
    def clean_messageStatus(self):
        if(self.isupdated):
            messageStatus=3
        else:
            messageStatus=2

        return messageStatus



    class Meta:
        model = Message
        fields = '__all__'

class HozurForm(forms.ModelForm):
    name=forms.CharField(widget=forms.Textarea())
   

    class Meta:
        model = HozurGhiab
        fields = '__all__'
class PersonelForm(forms.ModelForm):

    class Meta:
        model = Personnel
        # fields = '__all__'
        fields = ['manager', 'saloon','PNumber','FName','LName','NCode','Father','title']

class MessageForm(forms.Form):
    body = forms.CharField(widget=forms.Textarea())
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

fish/myapp/views/dashboardview.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.template.loader import render_to_string
from myapp.business.UserUtility import *
from django.contrib.auth.decorators import login_required
from myapp.models import SysUser
# @login_required
def index(request):
    month=['فروردین','ارديبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند']
    # UserUtility.get_user_list(request)
    # return render(request,"myapp/index.html",{"today" : today})
    return render(request,"myapp/entrance/login.html",{"today" : month})

fish/myapp/views/folderview.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.db.models import Sum
import jdatetime
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.views.decorators import csrf
import django.core.serializers
import logging
from django.conf import settings
from myapp.models.users import *
from django.views import View
import json
from django.forms.models import model_to_dict
from myapp.forms import SysUserForm
# from myapp.forms import SysUserImageForm
from django.urls import reverse_lazy
from django.db import transaction
from django.views.decorators.csrf import csrf_exempt
from myapp.business.mail import Mail
from myapp.business.UserUtility import *
from django.contrib.auth.decorators import login_required
from myapp.business.DateJob import *
from django.core.paginator  import *
from django.contrib.auth.models import User
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

def list_folder(request):
    return render(request, 'myapp/folders/folderList.html', {})

fish/myapp/templates/myapp/personel/att.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>حضور غیاب روزانه</title>
    <link rel="stylesheet" href="{% static 'css/persian-datepicker.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="{% static 'css/style.css'%}" rel="stylesheet">

    <style>
        body{
            direction:rtl;
            text-align:justify
        }
        .modal-container {
            overflow-y: auto;
          }
        
          
    </style>
</head>
<body>
 {% include 'myapp/personel/menu.html' %}
    <div class="container mt-5">
        <div id="part1">
            
            <div class="form-inline">
                <div class="form-group mb-2">
                    <label for="selected_date">انتخاب تاریخ</label>
                </div>
              
            </div>
            <div class="form-group">
               
                
            </div>
            <div class='form-group'>
                <div class="input-group-append d-flex justify-content-center">
                    <input type="text" class="form-control normal-example" id="selected_date" required >
 
                    <button id="nextBtn" class="btn btn-primary mx-1" style='background-color: #E8EAF6;
                    color: black;'> صبح</button>
                    <button id="button2" class="btn btn-secondary mx-1" style='background-color:#3F51B5
                    '>ظهر</button>
                    <button id="button3" class="btn btn-info mx-1" style='background-color:#1A237E'> شب</button>
                </div>
            </div>
            
        </div>
        
        <div id="part2" >
            {% comment %} <h2>Part 2 - Daily Attendance</h2> {% endcomment %}
            {% comment %} <h3>Date: <span id="selected_date_display"></span></h3> {% endcomment %}
            <form id="attendanceForm">
                <div class="table-responsive table-container">
                    <table class="table table-responsive-sm table-hover  table-bordered">
                        <thead>
                            <tr>
                                
                                <th class="fixed-column">نام</th>
                                <th>کد</th>
                                <th>سمت</th>
                                <th>حضور</th>
                                <th>استحقاقی</th>
                                <th>استعلاجی</th>
    
                                <th>ورود</th>
                                <th>خروج</th>
                                
                            </tr>
                        </thead>
                        <tbody id='tbody-company'> 
                            {% include 'myapp/personel/partialattview.html' %}
                        </tbody>
                    </table>
                    <button type="button" class="btn btn-primary fixed" id='btn-send'>ارسال</button>
                    
                </div>
               
            </form>
            <div class="modal fade" id="modal-company">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">عنوان</h5>
                            <button type="button" class="close" data-dismiss="modal">
                                <span>&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                        </div>
                        <div class="modal-footer">
                            <p>لطفا چند لحظه صبر نمایید</p>
                            <button type="button" class="btn btn-danger light" data-dismiss="modal">
                                بستن
                            </button>
                            <button type="button" class="btn btn-primary">دخیره</button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    
    <script src="{% static 'js/project/calendar/persian-date.js' %}"></script>
      
    <script src="{% static 'js/project/calendar/persian-datepicker.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{% static 'js/project/att.js'  %}" ></script>

   
</body>
</html>

fish/myapp/templates/myapp/personel/hozurdetaillist.html
<!--pip install django-widget-tweaks-->
{% extends 'myapp/index.html' %}
{% block style %}
@media print {
    body * {
        display: none;
    }
    table {
        display: table;
    }
}
{% endblock%}
 {% block content %}
{% load static %}
<div class="row">
  
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">جدول حضور غیاب {{date}} {{manager_name}}</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover table-responsive-sm">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>نام</th>
                            <th>کد</th>
                            <th>سمت</th>
                            <th>حضور</th>
                            <th>استحقاقی</th>
                            <th>استعلاجی</th>

                            <th>ورود</th>
                            <th>خروج</th>
                        </tr>
                        </thead >
                        <tbody id="tbody_hozur">
                       {% include 'myapp/personel/partialhozurdetailist.html' %}
                        </tbody>
                    </table>
                    <p>
                        
                                <button class="btn-danger js-delete-personel" data-url="manager={{manager}}&hdate={{hdate}}">حدف</button>
                            </div>
                        
                    </p>
                </div>
            </div>
        </div>
    </div>
    
</div>
<script>
    $(document).ready(function () {
        $("#main_search").on("keyup", function () {
            var searchText = $(this).val().toLowerCase();

            $(".data-row").each(function () {
                var rowData = $(this).text().toLowerCase();
                if (rowData.indexOf(searchText) === -1) {
                    $(this).hide();
                } else {
                    $(this).show();
                }
            });
        });
        $(".js-delete-personel").click(function(){
            a=confirm("حدف شود؟");
            if(a){
                const dst_url=$(this).data('url');
                $.ajax({
                    url:`/Hozur/Delete?${dst_url}`,
                    method:'get',
                    success:function(data){
                        if(data.form_is_valid)
                            $("#tbody_hozur").html('');
                    }
                });
            }
        });
    });
</script>
{% endblock %}

fish/myapp/templates/myapp/personel/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">ریسندگی خاطره کاشان</a>
    
    <!-- Hamburger Icon (visible on mobile screens) -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    
    <!-- Navigation Links -->
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="#">{{user}} عزیز خوش آمدید <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item"> 
                <a class="nav-link js-create-hozur2" data-url="{% url 'hozur_create' %}"  href="#" >جدید</a>
            </li>
           
        </ul>
    </div>
</nav>

fish/myapp/templates/myapp/personel/partialHozurCreate.html
<div id="hozurform" method="post" action="{% url 'hozur_create' %}" class="js-hozur-create-form" >
    {% csrf_token %}
    <div class="modal-header " style="background:#ccc">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4 class="modal-title">جدید</h4>
    </div>
    <div class="modal-body">
     {% include 'myapp/personel/partialHozurForm.html' %}
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">انصراف</button>
      <button type="button" class="btn btn-primary js-add-to-table" >ذخیره</button>
    </div>
</div>
  

fish/myapp/templates/myapp/personel/partialhozurdetailist.html
{% for personnel in personnel_list %}
<tr data-url={{personnel.person.id}} class='data-row' 
{% if personnel.is_ezafekar %}
style="background-color: #eec8afbb;"
{% endif %}

>
    <td>
        {{ forloop.counter }}
    </td>
    <td>{{ personnel.person.FName }} {{personnel.person.LName}}</td>
    <td>{{ personnel.person.PNumber }}</td>
    <td>{{personnel.get_title_display}}</td>
    <td>{% autoescape off %}{{personnel.get_hozur}}{% endautoescape %}</td>
    <td>{% autoescape off %}{{personnel.get_estehghaghi}}{% endautoescape %}</td>

    <td>{% autoescape off %}{{personnel.get_estelaji}}{% endautoescape %}</td>
    {% if personnel.hozur %}
    <td>{{personnel.incom_time|time:'G:i:s'}}</td>
    <td>{{personnel.outcome_time|time:'G:i:s'}}</td>
    {% else %}
    <td><span>-----</span></td>
    <td><span>----</span></td>
    {% endif %}

</tr>
{% endfor %}

fish/myapp/templates/myapp/personel/partialmanagername.html
{% for i in ps %}
<option value={{i.id}}>{{i}}</option>
{% endfor%}