fish/fish/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('myapp.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fish/myapp/urls.py
from django.urls import path
from myapp.views import *
from django.conf.urls import url
from django.contrib.auth.views import LoginView,LogoutView

from . import views

urlpatterns = [
    path(        'login/',        LoginView.as_view(            template_name="myapp/registration/login.html",            ),        name='login'),
    path(        'logout/',        LoginView.as_view(            template_name="myapp/registration/logout.html",            ),        name='logout'),

    path('', index, name='index'),
    path('userlogin/', user_login2, name='user_login'),
    path('managerlogin/', user_login3, name='user_login3'),

    url(r'^User/$',list_user,name='list_user'),
    url(r'^User/create/$', user_create, name='user_create'),
    url(r'^User/(?P<id>\d+)/update/$', user_update, name='user_update'),
    url(r'^User/(?P<id>\d+)/delete/$', user_delete, name='user_delete'),
    url(r'^Folder/$', list_folder, name='list_folder'),
    url(r'^Mail/$',list_mail,name='list_mail'),
    url(r'^Fish/$',list_fish,name='list_fish'),
    url(r'^Fish/Search/$',search_fish,name='search_fish'),
    url(r'^Fish/Upload$',fish_upload2,name='fish_upload'),
    url(r'^Fish/Create$',fish_create,name='fish_create'),
    url(r'^Fish/Process$',processfile,name='processfile'),
    url(r'^Fish/(?P<id>\d+)/Delete$',fish_delete,name='fish_delete'),


    url(r'^Fish/Detail$',details_fish,name='details_fish'),
    url(r'^Mail/create/$', mail_create, name='mail_create'),
    url(r'^Fish/(?P<id>\d+)/shekayat/$', register_shekayat, name='register_shekayat'),
    url(r'^Mail/(?P<id>\d+)/delete/$', mail_delete, name='mail_delete'),
    url(r'^Mail/(?P<id>\d+)/update/$', mail_update, name='mail_update'),
    url(r'^Mail/Sent/$', list_sentmail, name='list_sentmail'),
    url(r'^Mail/Status/$', list_unread_mail, name='list_unread_mail'),
    url(r'^Mail/System/$', list_sysmail, name='list_sysmail'),
    url(r'^MailFile/$', file_upload, name='file_upload'),
    url(r'^upload/$', handle_file_upload, name='handle_file_upload'),
    url(r'^file/$', file_upload_doc, name='file_upload_doc'),
    url(r'^personel/upload/$', insert_personel_data_from_csv, name='insert_personel_data_from_csv'),
    url(r'^personel/files/(?P<id>\d+)/remove$', remove_person_file, name='remove_person_file'),
    url(r'^personel/files/$', login_to_load_file, name='login_to_load_file'),
    url(r'^personel/$', list_personel, name='list_personel'),
    url(r'^personel/brief$', list_personel_breif, name='list_personel_breif'),
    url(r'^personel/brief/All$', list_personel_breif_all, name='list_personel_breif_all'),
    url(r'^personel/brief/getInfo$', get_personel_breig_info, name='get_personel_breig_info'),
    url(r'^personel/brief/getInfo/All$', get_personel_breig_info_all, name='get_personel_breig_info_all'),
    url(r'^personel/(?P<id>\d+)/profile$', view_profile, name='view_profile'),
    url(r'^personel/Att$', view_att, name='view_att'),
    url(r'^personel/SaveInfo/$', save_personel_att, name='save_personel_att'),
    url(r'^personel/GetMamnager$', get_manager_by_makan, name='get_manager_by_makan'),

    url(r'^personel/LoadDate/$', view_att, name='view_att'),
    url(r'^personel/(?P<id>\d+)/Delete$', delete_personel, name='delete_personel'),
    url(r'^personel/(?P<id>\d+)/Suspend$', suspend_personel, name='suspend_personel'),
    url(r'^Hozur/create/$', hozur_create, name='hozur_create'),
    url(r'^Hozur/GetTitles/$', getTitle, name='getTitle'),
    url(r'^Hozur/Calendar/$', show_hozur_calendar, name='show_hozur_calendar'),
    url(r'^Hozur/GetInfo/$', get_personel_calendar_info, name='get_personel_calendar_info'),
    url(r'^Hozur/GetDetails/$', get_hozur_list_detail, name='get_hozur_list_detail'),
    url(r'^Profile/Create/$', personel_create, name='create_profile'),
    url(r'^Profile/(?P<id>\d+)/Update/$', update_personel, name='update_personel'),
    url(r'^personel/Search/$',search_personel,name='search_personel'),
    url(r'^Hozur/Success/$',show_hozur_success,name='show_hozur_success'),
    url(r'^Hozur/Delete$',hozur_delete,name='hozur_delete'),
    url(r'^api/v1/assets$',list_assets,name='list_assets'),
    url(r'^api/v1/ita$',send_ita_view,name='send_ita_view'),







]

fish/myapp/models/assetcategory.py
from django.db import models


class AssetCategory(models.Model):
    name=models.CharField("نام",max_length = 50)
    code=models.CharField("کد",max_length = 50)
    description=models.CharField("توضیحات",max_length = 50)
    priority=models.IntegerField("اولویت", null=True)
    isPartOf = models.ForeignKey('self',on_delete=models.CASCADE,verbose_name="زیر مجموعه",null=True,blank=True)
    def __str__(self):
        return self.name

    class Meta:
       db_table = "assetcategory"

fish/myapp/models/fish.py
from django.db import models
from myapp.models.users import *
class Fish(models.Model):

    # khalese_pardakhti = models.CharField("خالص پرداختی",max_length=255,blank=True,null=True)
    # jame_kosurat = models.CharField("جمع کسورات",max_length=255,blank=True,null=True)
    # sayere_kosurat = models.CharField("سایر کسورات",max_length=255,blank=True,null=True)
    # vam = models.CharField("وام",max_length=255,blank=True,null=True)
    #
    #
    #
    # nakhalese_pardakhti = models.CharField("ناخالص پرداختی",max_length=255,blank=True,null=True)
    # sayere_mazaya = models.CharField("سایر مزایا",max_length=255,blank=True,null=True)




    def get_bime(self):
        return "{:,.0f}".format((float(self.monthly_hoghugh)+float(self.bon)+float(self.maskan))*0.07)
    def get_karkard(self):
        if(float(self.daily_hoghugh)==0):
            return 0
        return float(self.monthly_hoghugh)/float(self.daily_hoghugh)
    def get_gheibat(self):
        if(int(self.mah)<=6):
            return 31-self.get_karkard()-float(self.estelaji)
        elif(int(self.mah)==12):
            return 29-self.get_karkard()-float(self.estelaji)
        else:
            return 30-self.get_karkard()-float(self.estelaji)

    def get_bime_simple(self):
        # return (float(self.monthly_hoghugh)+float(self.bon)+float(self.maskan))*0.07
        return float(self.haghe_bime)
    def get_majmu_kosurat(self):
        return "{:,.0f}".format(self.get_majmu_kosurat_simple())
    def get_pardakhtha(self):
        return "{:,.0f}".format(self.get_pardakhtha_simple())
    def get_majmu_kosurat_simple(self):
        return self.get_bime_simple()+(float(self.maliat)+float(self.pool_khurd)+float(self.vame_dakheli)+float(self.vame_aghsati)+float(self.bime_azad)+float(self.bime_takmili)+float(self.kasre_hoghugh)+float(self.jarime)+float(self.mosaede))
    def get_pardakhtha_simple(self):
        return (float(self.haghe_tahol)+float(self.monthly_hoghugh)+float(self.ovlad)+float(self.ovlad_moavaghe)+float(self.randeman)+float(self.maskan)+float(self.bon)+float(self.ezafe_kar)+float(self.paye_sanavat)+float(self.jome_kari)+float(self.ravande_mahe_ghabl)+float(self.nobate_kari)+float(self.eslahe_hoghugh)+float(self.padash))
    def get_daryafti(self):
        return "{:,.0f}".format(self.get_pardakhtha_simple()-self.get_majmu_kosurat_simple())


    sal = models.CharField("خالص پرداختی",max_length=255,blank=True,null=True)
    mah = models.CharField("خالص پرداختی",max_length=255,blank=True,null=True)
    shekayat= models.CharField("مانده مرخصی",max_length=255,blank=True,null=True)
    mande_morakhasi= models.CharField("مانده مرخصی",max_length=255,blank=True,null=True)
    estelaji= models.CharField("استعلاجی",max_length=255,blank=True,null=True)
    ezafe_kar_time= models.CharField("اضافه کار",max_length=255,blank=True,null=True)
    morakhasi= models.CharField("مرخصی",max_length=255,blank=True,null=True)
    pool_khurd= models.CharField("پول خورد",max_length=255,blank=True,null=True)
    jarime= models.CharField("جریمه",max_length=255,blank=True,null=True)
    bime_azad= models.CharField("بیمه آزاد",max_length=255,blank=True,null=True)
    vame_aghsati= models.CharField("وام اقساطی",max_length=255,blank=True,null=True)
    bime_takmili= models.CharField("بیمه تکمیلی",max_length=255,blank=True,null=True)
    vame_dakheli= models.CharField("وام داخلی",max_length=255,blank=True,null=True)
    kasre_hoghugh= models.CharField("کسر حقوق",max_length=255,blank=True,null=True)
    mosaede = models.CharField("مساعده",max_length=255,blank=True,null=True)
    haghe_bime = models.CharField("حق بیمه",max_length=255,blank=True,null=True)
    maliat = models.CharField("مالیات",max_length=255,blank=True,null=True)
    ravande_mahe_ghabl = models.CharField("روند ماه قبل",max_length=255,blank=True,null=True)
    jome_kari = models.CharField("جمعه کاری",max_length=255,blank=True,null=True)
    randeman = models.CharField("راندمان",max_length=255,blank=True,null=True)
    eslahe_hoghugh = models.CharField("اصلاح حقوق",max_length=255,blank=True,null=True)
    padash = models.CharField("پاداش",max_length=255,blank=True,null=True)


    ezafe_kar = models.CharField("اضافه کار",max_length=255,blank=True,null=True)
    nemidunam = models.CharField("??",max_length=255,blank=True,null=True)
    ovlad = models.CharField("اولاد",max_length=255,blank=True,null=True)
    ovlad_moavaghe = models.CharField("اولاد معوقه",max_length=255,blank=True,null=True)
    paye_sanavat = models.CharField("پایه سنوات",max_length=255,blank=True,null=True)
    nobate_kari = models.CharField("نوبت کاری",max_length=255,blank=True,null=True)
    maskan= models.CharField("مسکن",max_length=255,blank=True,null=True)
    bon = models.CharField("بن",max_length=255,blank=True,null=True)

    monthly_hoghugh = models.CharField("حقوق ماهانه",max_length=255,blank=True,null=True)
    karkard = models.CharField("کارکرد به روز",max_length=255,blank=True,null=True)

    daily_hoghugh = models.CharField("حقوق روزانه",max_length=255,blank=True,null=True)
    name = models.CharField("نام",max_length=255,blank=True,null=True)
    code_meli = models.CharField("کد ملی",max_length=255,blank=True,null=True)
    code = models.CharField("کد پرسنلی",max_length=255,blank=True,null=True)
    haghe_tahol=models.CharField("حق تاهل",max_length=255,default='0')
    tatil_kar=models.CharField("تعطیل کار",max_length=255,default='0')







    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table="fish"
        ordering = ('date_added',)
class Person(models.Model):
    pid = models.CharField(max_length=20)
    name = models.CharField(max_length=100)
    codemeli = models.CharField(max_length=100)
class Salary(models.Model):
    sal = models.IntegerField()
    index = models.IntegerField()
    mah = models.IntegerField()
    person = models.ForeignKey(Person,related_name='salary_person', on_delete=models.CASCADE,null=True,blank=True)
    # fish = models.FileField(upload_to=file_upload_path)
    fishFile=models.FileField(upload_to='documents/%Y/%m/%d',max_length=200)
    def __str__(self):
        return f"Salary for {self.person.name}"
    class Meta:
        db_table="salary2"

fish/myapp/models/message.py
from django.db import models
from myapp.models import SysUser
from datetime import datetime
from django.utils.timezone import now
import jdatetime
import os
class Message(models.Model):
    read=3
    unread=2
    MessageStatus=(
    (read,'read'),
    (unread,'unread')
    )
    Highest=1
    High=2
    Medium=3
    Low=4
    Lowest=5
    Priority=(
        (Highest,'خیلی زیاد'),
        (High,'زیاد'),
        (Medium,'متوسط'),
        (Low,'پایین'),
        (Lowest,'خیلی پایین'),
    )
    def getdate(self):
        if self.sentTime.date()==datetime.now():
            return "{}".format(self.datetime.time())
        else:
            return jdatetime.date.fromgregorian(date=self.sentTime)
    msgPririty=models.IntegerField("پیامهای سیستمی",choices=Priority,null=True,blank=True)
    messageStatus=models.IntegerField("وضعیت",choices=MessageStatus)
    sentTime=models.DateTimeField(auto_now_add=True)
    fromUser=models.ForeignKey(SysUser,on_delete=models.CASCADE,related_name="fromuser",verbose_name="از:")
    toUser=models.ForeignKey(SysUser,on_delete=models.CASCADE,related_name="touser",verbose_name="به:")
    subject=models.CharField("موضوع",max_length=200,blank=True,null=True)
    Message=models.TextField(null=True,blank=True)
    class Meta:
        db_table="message"

class MessageFile(models.Model):
    def get_ext(self):
        v=os.path.splitext(self.woFile.name)
        return v[len(v)-1]
    def get_name(self):
        return os.path.basename(str(self.msgFile))
    def get_size(self):
        return " MB {0:.2f}".format(self.woFile.size/1048576)

    msgFile=models.FileField(upload_to='documents/%Y/%m/%d',max_length=200)
    msgFileworkorder=models.ForeignKey(Message,on_delete=models.CASCADE,blank=True,null=True)
    msgFiledateAdded=models.DateTimeField(auto_now_add=True)
    sal = models.IntegerField()
    mah = models.IntegerField()
    class Meta:
        db_table="messagefile"
class MessageFile2(models.Model):
    def get_ext(self):
        v=os.path.splitext(self.woFile.name)
        return v[len(v)-1]
    def get_name(self):
        return os.path.basename(str(self.msgFile))
    def get_size(self):
        return " MB {0:.2f}".format(self.woFile.size/1048576)

    msgFile=models.FileField(upload_to='documents/%Y/%m/%d',max_length=200)
    msgFileworkorder=models.ForeignKey(Message,on_delete=models.CASCADE,blank=True,null=True)
    msgFiledateAdded=models.DateTimeField(auto_now_add=True)
    sal = models.IntegerField()
    mah = models.IntegerField()
    class Meta:
        db_table="messagefile2"

fish/myapp/models/msg.py
from django.db import models
from myapp.models.users import *
class Msg(models.Model):
    fromUser=models.ForeignKey(SysUser,on_delete=models.CASCADE,related_name="fromuser1",verbose_name="از:",default=1)
    toUser=models.ForeignKey(SysUser,on_delete=models.CASCADE,related_name="touser1",verbose_name="به:",default=1)
    room = models.CharField(max_length=255)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table="msg"
        ordering = ('date_added',)

fish/myapp/forms.py
from django import forms
from myapp.models import *
from django.conf import settings
import logging
from django.forms import ModelForm, inlineformset_factory
from django.contrib.auth.models import Group
class SysUserForm(forms.ModelForm):
    #CustomerId = forms.ModelChoiceField(queryset=Customer.objects.all())



    class Meta:
        model = SysUser
        fields = '__all__'
class MessageForm(forms.ModelForm):
    toUser = forms.ModelChoiceField(label="مخاطب",queryset=SysUser.objects.all(),empty_label='به کی')
    def clean_messageStatus(self):
        if(self.isupdated):
            messageStatus=3
        else:
            messageStatus=2

        return messageStatus



    class Meta:
        model = Message
        fields = '__all__'

class HozurForm(forms.ModelForm):
    name=forms.CharField(widget=forms.Textarea())
   

    class Meta:
        model = HozurGhiab
        fields = '__all__'
class PersonelForm(forms.ModelForm):

    class Meta:
        model = Personnel
        # fields = '__all__'
        fields = ['manager', 'saloon','PNumber','FName','LName','NCode','Father','title']

class MessageForm(forms.Form):
    body = forms.CharField(widget=forms.Textarea())
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

fish/myapp/views/dashboardview.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.template.loader import render_to_string
from myapp.business.UserUtility import *
from django.contrib.auth.decorators import login_required
from myapp.models import SysUser
# @login_required
def index(request):
    month=['فروردین','ارديبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند']
    # UserUtility.get_user_list(request)
    # return render(request,"myapp/index.html",{"today" : today})
    return render(request,"myapp/entrance/login.html",{"today" : month})

fish/myapp/views/folderview.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.db.models import Sum
import jdatetime
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.views.decorators import csrf
import django.core.serializers
import logging
from django.conf import settings
from myapp.models.users import *
from django.views import View
import json
from django.forms.models import model_to_dict
from myapp.forms import SysUserForm
# from myapp.forms import SysUserImageForm
from django.urls import reverse_lazy
from django.db import transaction
from django.views.decorators.csrf import csrf_exempt
from myapp.business.mail import Mail
from myapp.business.UserUtility import *
from django.contrib.auth.decorators import login_required
from myapp.business.DateJob import *
from django.core.paginator  import *
from django.contrib.auth.models import User
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

def list_folder(request):
    return render(request, 'myapp/folders/folderList.html', {})

fish/myapp/templates/myapp/fish/fishList.html
<!--pip install django-widget-tweaks-->
{% extends 'myapp/index.html' %}

 {% block content %}
{% load static %}
<div class="page-titles">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">اطلاعات فیش</a></li>
                    <li class="breadcrumb-item active"><a href="javascript:void(0)">لیست فیش</a></li>
                </ol>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">

                            <div class=" ml-0 ml-sm-4 ml-sm-0">

                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered table-responsive-sm " id="table-company">
                                        <thead>
                                        <tr>
                                          <th>عنوان</th>
                                          <th>سال</th>
                                          <th>عملیات</th>

                                        </tr>
                                        </thead>
                                        <tbody id="orders">
                                    {% include 'myapp/fish/partialFishList.html' %}
                                        </tbody>
                                    </table>
                                </div>

                                <!-- panel -->

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">

                        </div>
                    </div>
                </div>
                <div class="row mt-4">
                                        <div class="col-12 pl-3">
                                            <nav>
                                                <ul class="pagination pagination-gutter pagination-primary pagination-sm no-bg">
                                                  {% if fishes.has_previous %}
                                                    <li class="page-item page-indicator"><a class="page-link" href="?page={{ fishes.previous_page_number }}"><i class="la la-angle-left"></i></a></li>
                                                    {% else %}
                                                    <li class="page-item page-indicator"><a class="page-link" href="#"><i class="la la-angle-left"></i></a></li>
                                                    {% endif %}
                                                      {% if fishes.has_next %}
                                                      <li class="page-item page-indicator"><a class="page-link" href="?page={{ fishes.next_page_number }}"><i class="la la-angle-right"></i></a></li>

                                                      {% else %}

                                                        <li class="page-item page-indicator"><a class="page-link" href="#"><i class="la la-angle-right"></i></a></li>
                                                      {% endif %}


                                                </ul>
                                            </nav>
                                        </div>
                                    </div>
            </div>
            <div class="modal fade" id="modal-shekayat" style="overflow-y: scroll">
               <div class="modal-dialog  modal-lg ">

                 <div class="modal-content ">
                 </div>
               </div>
              </div>

{% load static %}

{% block javascript %}
  <script src="{% static '/js/project/fish.js' %}"></script>


{% endblock %}
{% endblock %}

fish/myapp/templates/myapp/fish/fishdetaile2.html
<!DOCTYPE html>
{% load static %}
{% load humanize %}
<html lang="fa">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="" />
    <meta name="author" content="" />
    <meta name="robots" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="پنل مدیریتی - داشبورد 1" />
    <meta property="og:title" content="پنل مدیریتی - داشبورد 1" />
    <meta property="og:description" content="پنل مدیریتی - داشبورد 1" />
    <meta property="og:image"  />
    <meta name="format-detection" content="telephone=no">
    <title>فیش حقوق {{mah}} ماه {{sal}}</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon.png' %}">
    <link href="{% static 'vendor/jqvmap/css/jqvmap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'vendor/chartist/css/chartist.min.css' %}">
    <!-- Vectormap -->
    <link href="{% static 'vendor/jqvmap/css/jqvmap.min.css'%}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-select/dist/css/bootstrap-select.min.css'%}" rel="stylesheet">
    <link href="{% static 'vendor/owl-carousel/owl.carousel.css'%}" rel="stylesheet">
    <link href="{% static '2.0/lineicons.css'%}" rel="stylesheet">
    <link href="{% static 'css/style.css'%}" rel="stylesheet">
    <link href="{% static 'vendor/dropzone/dist/dropzone.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'js/jquery-2.1.1.js' %}"></script>
    <style>
        table.table-bordered{
    border:1px solid blue;
    margin-top:20px;
  }
table.table-bordered > thead > tr > th{
    border:1px solid blue;
}
table.table-bordered > tbody > tr > td{
    border:1px solid blue;
}
table.table-bordered > tfoot > tr > th{
    border:1px solid blue;
}
        /* Custom CSS to add margins */
        .custom-margin {
          margin: 50px auto; /* Adjust the margin values as needed */
        }

body{
    font-size: 0.70rem;
    background-color: white;
}
.bold-text {
      font-weight: bold;
    }
    .centered-button {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
  }
.custom-table td {
      padding: 0.20rem; /* Adjust the padding value as needed */
    }
    @media print {
      body {
        width: 148mm; /* A5 width */
        height: 210mm; /* A5 height */
        margin: 0; /* Reset margins */
      }

      @page {
        size: A5 landscape; /* Set A5 size and landscape orientation */
        margin: 5mm; /* Adjust margin as needed */
      }
    }
      </style>

    <script type="text/javascript">
      window.RAYCHAT_TOKEN = "f498c874-46cd-43bb-844f-d6a2c3e25a0b";
        (function () {
          d = document;
          s = d.createElement("script");
          s.src = "https://widget-react.raychat.io/install/widget.js";
          s.async = 1;
          d.getElementsByTagName("head")[0].appendChild(s);
        })();
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.14.0/pdf.min.js"></script>

</head>
<body>
    <div class="container mt-4">

        <div class="row justify-content-center custom-margin">
          <div class="col-lg-9">
            <div class="row">
                <div class="col-md-4"> <h6>{{person.name}} </h6> </div>
                <div class="col-md-4"> <h6>{{mah}} ماه {{sal}} </h6> </div>
                <div class="col-md-4"> <h6>کد پرسنلی:{{person.pid}}</h6> </div>
            </div>
            <div class='row'>
              <div class='col-lg-4'></div>
              <div class='col-lg-4'>
                <a href="{% get_media_prefix %}{{pdf}}"><button type="button" class="btn btn-secondary mt-4">دانلود <span class="btn-icon-right"><i class="fa fa-envelope"></i></span>
                </button></a>
              </div>
              <div class='col-lg-4'>
              </div>
            </div>






          </div>
        </div>

      </div>



<!-- Bootstrap JS (Optional - for certain Bootstrap functionalities) -->
<script src="{% static 'vendor/global/global.min.js'%}"></script>
<!-- Chart piety plugin files -->
<!-- Dashboard 1 -->
<script src="{% static 'js/deznav-init.js'%}"></script>

</body>
</html>

fish/myapp/templates/myapp/fish/partialFishList.html
{% load humanize %}

{% for c in fishes %}
<tr class="btn-reveal-trigger">
  <td>حقوق ماه {{c.mah}}</td>
  <td>{{c.sal}}</td>
    <td class="py-2">

        <div class="dropdown text-sans-serif">
            <button class="btn btn-primary tp-btn-light sharp" type="button" id="order-dropdown-0" data-toggle="dropdown" data-boundary="viewport" aria-haspopup="true" aria-expanded="false"><span><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="18px" height="18px" viewBox="0 0 24 24" version="1.1"><g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><rect x="0" y="0" width="24" height="24"></rect><circle fill="#000000" cx="5" cy="12" r="2"></circle><circle fill="#000000" cx="12" cy="12" r="2"></circle><circle fill="#000000" cx="19" cy="12" r="2"></circle></g></svg></span>
            </button>
            <div class="dropdown-menu dropdown-menu-right border py-0" aria-labelledby="order-dropdown-0">
                {% if perms.myapp.delete_fish %}
                <div class="py-2">

                    <a class="dropdown-item text-danger js-profile-delete" href="#!" data-url="{% url 'fish_delete' c.id %}">حذف</a>
                </div>
                {% endif %}
            </div>
        </div>
    </td>
</tr>
{% endfor %}

fish/myapp/templates/myapp/fish/partialMailDelete.html
<form method="post" action="{% url 'mail_delete' mail.id %}" class="js-mail-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">حذف</h4>
  </div>
  <div class="modal-body">
    <p class="lead">از عمل حذف مطمین هستید؟  <strong>{{ mail.id }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-danger"> حذف</button>
    <button type="button" class="btn btn-default" data-dismiss="modal">بستن</button>
  </div>
</form>